# src/infrastructure/web/swagger/definitions/common.yml
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
              value:
                type: any
      required:
        - error

    PaginationResponse:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
        totalPages:
          type: integer
          minimum: 0
        total:
          type: integer
          minimum: 0
        limit:
          type: integer
          minimum: 1

    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [ADMIN, INSTRUCTOR, STUDENT]
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Profile:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        name:
          type: string
        bio:
          type: string
          nullable: true
        profilePhoto:
          type: string
          nullable: true
        languageLevel:
          type: string
          enum: [N5, N4, N3, N2, N1]
          nullable: true
        points:
          type: integer
          minimum: 0
        badges:
          type: array
          items:
            type: string
        level:
          type: integer
          minimum: 1
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Course:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [JAPAN_IN_CONTEXT, JLPT_IN_CONTEXT]
        icon:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Lesson:
      type: object
      properties:
        id:
          type: string
        courseId:
          type: string
        title:
          type: string
        description:
          type: string
        order:
          type: integer
          minimum: 1
        videoUrl:
          type: string
          nullable: true
        audioFiles:
          type: array
          items:
            type: string
        resources:
          type: array
          items:
            type: string
        requiresReflection:
          type: boolean
        pointsReward:
          type: integer
          minimum: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Session:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [SPEAKING, EVENT]
        hostId:
          type: string
        meetingUrl:
          type: string
          nullable: true
        scheduledAt:
          type: string
          format: date-time
        duration:
          type: integer
          description: Duration in minutes
        maxParticipants:
          type: integer
          minimum: 1
        currentParticipants:
          type: integer
          minimum: 0
        pointsRequired:
          type: integer
          minimum: 0
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Post:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        content:
          type: string
        mediaUrls:
          type: array
          items:
            type: string
        isAnnouncement:
          type: boolean
        likesCount:
          type: integer
          minimum: 0
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Booking:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        sessionId:
          type: string
        status:
          type: string
          enum: [CONFIRMED, CANCELLED, COMPLETED]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Progress:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        lessonId:
          type: string
        courseId:
          type: string
        isCompleted:
          type: boolean
        completedAt:
          type: string
          format: date-time
          nullable: true
        reflectionSubmitted:
          type: boolean
          nullable: true
        quizScore:
          type: number
          format: float
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
